---
openapi: "3.0.1"
info:
  title: "Syntax Editor"
  description: "Script editor API to get context menu items"
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/syntax_editor/cache/{token_type}:
    get:
      description: ""
      parameters:
      - name: "token_type"
        in: "path"
        required: true
        schema: {}
      - name: "name"
        in: "query"
        description: "Name"
        required: false
        schema: {}
        example: "incident"
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/syntax_editor/completions:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/syntax_editor/getReferences:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/syntax_editor/intellisense/{tableName}:
    post:
      description: ""
      parameters:
      - name: "tableName"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
