---
openapi: "3.0.1"
info:
  title: "Stream Attachment Utils API"
  description: "Get the attachment status"
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/as_attachment/getAvailability/{sys_id}:
    get:
      description: ""
      parameters:
      - name: "sys_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
