---
openapi: "3.0.1"
info:
  title: "Mobile GenAI API"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/generative/wwna_action_execute:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/generative/wwna_action_poll:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/generative/wwna_skill_config:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
