---
openapi: "3.0.1"
info:
  title: "VA bot uninstall"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/va_bot_uninstall/{clientType}/{externalId}:
    get:
      description: ""
      parameters:
      - name: "clientType"
        in: "path"
        required: true
        schema: {}
      - name: "externalId"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
