---
openapi: "3.0.1"
info:
  title: "ATF Agent"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/atf_agent/online:
    get:
      description: ""
      parameters:
      - name: "id"
        in: "query"
        description: "ID of the sys_atf_agent to check"
        required: false
        schema: {}
        example: ""
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
