---
openapi: "3.0.1"
info:
  title: "Contextual Search (Internal API)"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/cxs/action_handler:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
  /api/now/cxs/feedback:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
  /api/now/cxs/feedback/link:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
  /api/now/cxs/get_actions_by_condition:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
  /api/now/cxs/get_latest_worknote/{table_name}/{record_id}:
    get:
      description: ""
      parameters:
      - name: "table_name"
        in: "path"
        required: true
        schema: {}
      - name: "record_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
  /api/now/cxs/search:
    get:
      description: ""
      parameters:
      - name: "start"
        in: "query"
        description: "The index of the first result to return"
        required: false
        schema: {}
        example: "1"
      - name: "cx"
        in: "query"
        description: "The search context, either sys_id or name"
        required: false
        schema: {}
        example: "Incident Deflection"
      - name: "num"
        in: "query"
        description: "The number of resuts to return"
        required: false
        schema: {}
        example: "10"
      - name: "q"
        in: "query"
        description: "Query String"
        required: false
        schema: {}
        example: "this AND that"
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
    post:
      description: ""
      parameters:
      - name: "q"
        in: "query"
        description: "Query String"
        required: false
        schema: {}
        example: "this AND that"
      - name: "cx"
        in: "query"
        description: "The search context, either sys_id or name"
        required: false
        schema: {}
        example: "Incident Deflection"
      - name: "start"
        in: "query"
        description: "The index of the first result to return"
        required: false
        schema: {}
        example: "1"
      - name: "num"
        in: "query"
        description: "The number of resuts to return"
        required: false
        schema: {}
        example: "10"
      requestBody:
        content:
          application/json: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
