---
openapi: "3.0.1"
info:
  title: "Change Request Calendar (Internal API)"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/change_request_calendar/change/nextavailabletime/{sys_id}:
    put:
      description: ""
      parameters:
      - name: "sys_id"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
    post:
      description: ""
      parameters:
      - name: "sys_id"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/change_request_calendar/change/related/{sys_id}:
    get:
      description: ""
      parameters:
      - name: "sys_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/change_request_calendar/change/{sys_id}/{start_date}/{end_date}:
    get:
      description: ""
      parameters:
      - name: "sys_id"
        in: "path"
        required: true
        schema: {}
      - name: "start_date"
        in: "path"
        required: true
        schema: {}
      - name: "end_date"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/change_request_calendar/glidestack/{action}:
    get:
      description: ""
      parameters:
      - name: "action"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/change_request_calendar/{table}/{sysid}:
    patch:
      description: ""
      parameters:
      - name: "table"
        in: "path"
        required: true
        schema: {}
      - name: "sysid"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
