---
openapi: "3.0.1"
info:
  title: "Conversation Message Resource"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/cs_message:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
