---
openapi: "3.0.1"
info:
  title: "Mobile User Client API"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/sg/user_client:
    get:
      description: "Get a User Client page"
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
