---
openapi: "3.0.1"
info:
  title: "Reporting Table Description API"
  description: "Allows you to perform get operation on table and field descriptions"
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/reporting_table_description/field_description/{table_name}:
    get:
      description: ""
      parameters:
      - name: "table_name"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/reporting_table_description/{table_name}:
    get:
      description: ""
      parameters:
      - name: "table_name"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
