---
openapi: "3.0.1"
info:
  title: "Mobile Custom Map API"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/sg/custom_map:
    post:
      description: "Returns a document with a custom map template containing the reference\
        \ list data."
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
