---
openapi: "3.0.1"
info:
  title: "ML Instance Validation"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/ml_instance_validation/validateToken/{token}:
    get:
      description: ""
      parameters:
      - name: "token"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
