---
openapi: "3.0.1"
info:
  title: "Conversation Server Preview"
  description: "API for enabling and disabling logging for conversation preview"
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/cs_preview/logging/{flag}:
    put:
      description: ""
      parameters:
      - name: "flag"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
