---
openapi: "3.0.1"
info:
  title: "CMDB UI API (Internal API)"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/cmdb_ui_api/IdentificationGetParentClasses/{className}:
    get:
      description: ""
      parameters:
      - name: "className"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/cmdb_ui_api/IdentificationLookUpTables/{className}:
    get:
      description: ""
      parameters:
      - name: "className"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/cmdb_ui_api/validate/{sys_id}:
    get:
      description: ""
      parameters:
      - name: "sys_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
