---
openapi: "3.0.1"
info:
  title: "Mobile Impersonation API"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/sg/impersonation/session:
    get:
      description: "Get impersonation details for current session."
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/impersonation/users:
    get:
      description: "Get Impersonation User List"
      parameters:
      - name: "start"
        in: "query"
        description: "Start index"
        required: false
        schema: {}
      - name: "filter"
        in: "query"
        description: "Search filter"
        required: false
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
