---
openapi: "3.0.1"
info:
  title: "Mobile REST API"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/sg/applications:
    get:
      description: "Get an array of applications"
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/document:
    post:
      description: "Post a document"
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/item:
    post:
      description: "Get Item"
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/list:
    post:
      description: "Get List"
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/migrate/madrid:
    post:
      description: "New schema migration"
      parameters:
      - name: "sysparm_scope"
        in: "query"
        description: "The scope sys_id"
        required: true
        schema: {}
      - name: "sysparm_client_type"
        in: "query"
        description: "The client type"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/pre_auth:
    get:
      description: "Pre-Authentication API"
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/preferences:
    get:
      description: "Mobile Get User Preferences"
      parameters:
      - name: "sysparm_pref_name"
        in: "query"
        description: "Specify preference key to get (can handle multiple keys in array)"
        required: false
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
    post:
      description: "Updating user preferences"
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/schedule/{user_id}:
    get:
      description: "Get an agent's schedule given user ID"
      parameters:
      - name: "user_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/validate_credentials:
    post:
      description: "Authentication API"
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/writeback:
    post:
      description: "Submit Action"
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
