---
openapi: "3.0.1"
info:
  title: "Mobile Offline API"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/sg/offline/generate:
    get:
      description: "Request mobile offline data to be immediately generated"
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/offline/incremental/{result_token}:
    get:
      description: "Retrieve incremental offline data updates"
      parameters:
      - name: "result_token"
        in: "path"
        required: true
        schema: {}
      - name: "lastUpdateTS"
        in: "query"
        description: "Timestamp of the latest update that the mobile client has already\
          \ received"
        required: false
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/offline/retrieve/{result_token}:
    get:
      description: "Retrieve previously requested mobile offline data"
      parameters:
      - name: "result_token"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/offline/schedule_generate:
    get:
      description: "Request mobile offline data to be scheduled to be generated"
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/offline/synchronize:
    post:
      description: "Synchronize"
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
