---
openapi: "3.0.1"
info:
  title: "PAR Scheduled Export"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/par_scheduled_export/delete/{export_id}:
    delete:
      description: ""
      parameters:
      - name: "export_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/par_scheduled_export/execute/{export_id}:
    get:
      description: ""
      parameters:
      - name: "export_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/par_scheduled_export/fetch/{export_id}:
    get:
      description: ""
      parameters:
      - name: "export_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/par_scheduled_export/save:
    post:
      description: "Inserts new scheduled job for export"
      parameters: []
      requestBody:
        content:
          application/json: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/par_scheduled_export/update/{export_id}:
    patch:
      description: ""
      parameters:
      - name: "export_id"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
