---
openapi: "3.0.1"
info:
  title: "CMDB Data Ingestion API"
  description: "Allows you to ingest an array of objects in batches"
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/cmdb/ingest/{data_source_sys_id}:
    post:
      description: "Create a record to be ingested by the CMDB"
      parameters:
      - name: "data_source_sys_id"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
