---
openapi: "3.0.1"
info:
  title: "Workspace Administration"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/workspace_administration/workspace_acl/{workspace_id}:
    get:
      description: ""
      parameters:
      - name: "workspace_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/workspace_administration/workspace_url/{workspace_id}:
    get:
      description: ""
      parameters:
      - name: "workspace_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
