---
openapi: "3.0.1"
info:
  title: "Wrap Up API"
  description: ""
  version: "v1"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/v1/wrapup/code:
    post:
      description: "Create Wrap Up Codes"
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/v1/wrapup/code/{code_id}:
    get:
      description: "Retrieve Wrap Up Code by ID"
      parameters:
      - name: "code_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/v1/wrapup/segment/agent/{agent_id}/interaction/{interaction_id}:
    get:
      description: "Retrieve Segment by Agent ID and Interaction ID"
      parameters:
      - name: "agent_id"
        in: "path"
        required: true
        schema: {}
      - name: "interaction_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/v1/wrapup/segment/create:
    post:
      description: "Create Wrap Up Segment"
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/v1/wrapup/segment/update:
    put:
      description: "Update Wrap Up Segment"
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/v1/wrapup/segment/{segment_id}:
    get:
      description: "Retrieve Segment by Sys ID/External Segment ID"
      parameters:
      - name: "segment_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
