---
openapi: "3.0.1"
info:
  title: "ActivitySubscriptions"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/actsub/activities:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/actsub/contexts:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/actsub/facets/{activity_context}/{context_instance}:
    get:
      description: ""
      parameters:
      - name: "activity_context"
        in: "path"
        required: true
        schema: {}
      - name: "context_instance"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/actsub/followings/{follower}:
    get:
      description: ""
      parameters:
      - name: "follower"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/actsub/preferences:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/actsub/preferences/{profileId}:
    get:
      description: ""
      parameters:
      - name: "profileId"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/actsub/subobjects:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/actsub/subscribers/{sub_object}:
    get:
      description: ""
      parameters:
      - name: "sub_object"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/actsub/subscriptions/{subscriber_id}:
    get:
      description: ""
      parameters:
      - name: "subscriber_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/actsub/subscriptions/{sub_obj_id}/isSubscribed:
    get:
      description: "Returns if current user is subscribed to the object"
      parameters:
      - name: "sub_obj_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/actsub/subscriptions/{sub_obj_Id}/subscribe:
    post:
      description: "This is to subscribe to the subscribable object"
      parameters:
      - name: "sub_obj_Id"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/actsub/subscriptions/{sub_obj_id}/unsubscribe:
    delete:
      description: "Remove subscription for the current user for the given object"
      parameters:
      - name: "sub_obj_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/actsub/userstream/{profileId}:
    get:
      description: ""
      parameters:
      - name: "profileId"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
    put:
      description: ""
      parameters:
      - name: "profileId"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
