---
openapi: "3.0.1"
info:
  title: "Conversation Member API"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/conversation/member/{user_id}/drop:
    put:
      description: "Drop agent from a conversation."
      parameters:
      - name: "user_id"
        in: "path"
        required: true
        schema: {}
      - name: "interaction_id"
        in: "query"
        description: "Interaction for which the agent needs to be dropped as a member."
        required: false
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/conversation/member/{user_id}/update:
    put:
      description: "Update agent's memberType in a conversation."
      parameters:
      - name: "user_id"
        in: "path"
        required: true
        schema: {}
      - name: "role"
        in: "query"
        description: "The role to which the member type needs to be updated to."
        required: false
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
