---
openapi: "3.0.1"
info:
  title: "CMDB Instance API"
  description: "Allows you to perform create, read and update operations on existing\
    \ CMDB tables"
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/cmdb/instance/{className}:
    get:
      description: "Query records for a CMDB class"
      parameters:
      - name: "className"
        in: "path"
        required: true
        schema: {}
      - name: "sysparm_query"
        in: "query"
        description: "An encoded query string used to filter the results"
        required: false
        schema: {}
      - name: "sysparm_limit"
        in: "query"
        description: "The maximum number of results returned per page (default: 1000)"
        required: false
        schema: {}
      - name: "sysparm_offset"
        in: "query"
        description: "A number of records to exclude from the query (default: 0)"
        required: false
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
    post:
      description: "Create a record with associated relations"
      parameters:
      - name: "className"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/cmdb/instance/{className}/{sys_id}:
    get:
      description: "Query attributes and relationship information for a specific record"
      parameters:
      - name: "className"
        in: "path"
        required: true
        schema: {}
      - name: "sys_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
    put:
      description: "Replace CI record"
      parameters:
      - name: "className"
        in: "path"
        required: true
        schema: {}
      - name: "sys_id"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
    patch:
      description: "Update CI record"
      parameters:
      - name: "className"
        in: "path"
        required: true
        schema: {}
      - name: "sys_id"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/cmdb/instance/{className}/{sys_id}/relation:
    post:
      description: "Create Relation for the CI"
      parameters:
      - name: "className"
        in: "path"
        required: true
        schema: {}
      - name: "sys_id"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/cmdb/instance/{className}/{sys_id}/relation/{rel_sys_id}:
    delete:
      description: "Delete Relation for the CI"
      parameters:
      - name: "className"
        in: "path"
        required: true
        schema: {}
      - name: "sys_id"
        in: "path"
        required: true
        schema: {}
      - name: "rel_sys_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
