---
openapi: "3.0.1"
info:
  title: "Predictive Intelligence"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/agent_intelligence/solution/prediction:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/agent_intelligence/solution/{solution_name}/prediction:
    get:
      description: ""
      parameters:
      - name: "solution_name"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/agent_intelligence/solution/{solution_name}/solution_cancel:
    get:
      description: ""
      parameters:
      - name: "solution_name"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/agent_intelligence/solution/{solution_name}/solution_getsolutionrecords:
    get:
      description: ""
      parameters:
      - name: "solution_name"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/agent_intelligence/solution_create_training_request:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/agent_intelligence/train_default_solutions:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/agent_intelligence/{trainer}/trainer_getoobsolutiondefinitions:
    get:
      description: ""
      parameters:
      - name: "trainer"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
