---
openapi: "3.0.1"
info:
  title: "TimeAgo"
  description: "TimeAgo Date Utils "
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/timeago/absolute:
    get:
      description: "Converts TimeAgo relative date/time to absolute date/time for\
        \ UI DateTime Filter"
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
