---
openapi: "3.0.1"
info:
  title: "SLA (Internal API)"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/sla/glidestack/{action}:
    post:
      description: ""
      parameters:
      - name: "action"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sla/sla_definition/{contractSlaIds}:
    get:
      description: ""
      parameters:
      - name: "contractSlaIds"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sla/timeline/{taskId}:
    get:
      description: ""
      parameters:
      - name: "taskId"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
