---
openapi: "3.0.1"
info:
  title: "Mobile Deep Link API"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/sg/deeplink/launch_button/{Payload}:
    get:
      description: "Get Button"
      parameters:
      - name: "Payload"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/deeplink/redirect/{Payload}:
    get:
      description: "Get Redirection"
      parameters:
      - name: "Payload"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
