---
openapi: "3.0.1"
info:
  title: "Mobile Applet Launcher API"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/sg/applet_launcher:
    get:
      description: "Get applet launcher"
      parameters:
      - name: "applet_launcher_id"
        in: "query"
        description: "Id of applet launcher"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/applet_launcher/feed:
    get:
      description: "Get several types of the live feeds on the applet launcher page"
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/applet_launcher/initialize:
    get:
      description: "Initialize the live feeds on the applet launcher page"
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/applet_launcher/refresh:
    get:
      description: "Refresh the live feeds on the applet launcher page"
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
