---
openapi: "3.0.1"
info:
  title: "SNHelpService"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/help/documents:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/help/documents/{sys_id}:
    get:
      description: "Get Embedded help content by sys_id of the embedded_help_content\
        \ record."
      parameters:
      - name: "sys_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/help/feedback:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/help/guidance/{guidance_id}:
    get:
      description: ""
      parameters:
      - name: "guidance_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/help/interactions/{id}:
    post:
      description: ""
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/help/resources:
    get:
      description: "Get the help resource from help content table "
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/help/wnstatus:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
