---
openapi: "3.0.1"
info:
  title: "Mobile Badge Count API"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/sg/badge_count:
    get:
      description: "Get multiple badge counts"
      parameters:
      - name: "sysparm_badge_count_ids"
        in: "query"
        description: "Badge count ids (comma separated)"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/badge_count/{badge_count_id}:
    get:
      description: "Get a single badge count"
      parameters:
      - name: "badge_count_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
