---
openapi: "3.0.1"
info:
  title: "Mobile Language API"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/sg/language:
    put:
      description: "Updates the current user's preferred language."
      parameters: []
      requestBody:
        content:
          application/json: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/language_bundle:
    get:
      description: "Get the language bundle for the user's preferred language."
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
  /api/now/sg/languages:
    get:
      description: "Returns a list of supported languages."
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
