---
openapi: "3.0.1"
info:
  title: "Mobile Favorites API"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/sg/favorite:
    get:
      description: "Get Favorites List"
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
    post:
      description: "Create Favorite item"
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/favorite/navigate/{favorite_id}:
    get:
      description: "Navigate to favorite screen"
      parameters:
      - name: "favorite_id"
        in: "path"
        required: true
        schema: {}
      - name: "time_zone_id"
        in: "query"
        description: "Time zone identifier"
        required: false
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/favorite/{favorite_id}:
    put:
      description: "Update Favorite item"
      parameters:
      - name: "favorite_id"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
    delete:
      description: "Delete Favorite item"
      parameters:
      - name: "favorite_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
