---
openapi: "3.0.1"
info:
  title: "Reporting Alias API"
  description: "Allows you to perform create, read and update operations on report\
    \ aliases"
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/reporting_alias/{report_id}:
    get:
      description: ""
      parameters:
      - name: "report_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
    post:
      description: ""
      parameters:
      - name: "report_id"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
