---
openapi: "3.0.1"
info:
  title: "MID Telemetry API"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/mid_telemetry/metrics:
    post:
      description: ""
      parameters:
      - name: "mid_sys_id"
        in: "query"
        description: "Sys ID to identify MID Server"
        required: true
        schema: {}
        example: ""
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
