---
openapi: "3.0.1"
info:
  title: "Mobile Universal Link API"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/sg/ulink/banner:
    get:
      description: "Get banner details"
      parameters:
      - name: "url"
        in: "query"
        description: "URL for retrieving banner details"
        required: false
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/sg/ulink/document:
    get:
      description: "Retrieve document from url"
      parameters:
      - name: "url"
        in: "query"
        description: "URL for retrieving document"
        required: false
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
