---
openapi: "3.0.1"
info:
  title: "Client Extension Point Service"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/clientextension/{name}:
    get:
      description: "Get all UI Scripts which are registered instances of a Client\
        \ Extension Point"
      parameters:
      - name: "name"
        in: "path"
        required: true
        schema: {}
      - name: "sysparm_scope"
        in: "query"
        description: "The scope of the extension point"
        required: false
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
