---
openapi: "3.0.1"
info:
  title: "Interactive Analysis (Internal API)"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/interactive_analysis/table/{tableName}:
    get:
      description: ""
      parameters:
      - name: "tableName"
        in: "path"
        required: true
        schema: {}
      - name: "sysparm_list_view"
        in: "query"
        description: "List's view name."
        required: false
        schema: {}
        example: ""
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
    post:
      description: ""
      parameters:
      - name: "tableName"
        in: "path"
        required: true
        schema: {}
      - name: "sysparm_list_view"
        in: "query"
        description: "List's view name."
        required: false
        schema: {}
        example: ""
      requestBody:
        content:
          application/json: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
    delete:
      description: ""
      parameters:
      - name: "tableName"
        in: "path"
        required: true
        schema: {}
      - name: "sysparm_list_view"
        in: "query"
        description: "List's view name."
        required: false
        schema: {}
        example: ""
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
