---
openapi: "3.0.1"
info:
  title: "Push Installation API"
  description: "Allows mobile applications to manage tokens to receive push notifications"
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/push/{pushApplicationName}/installation:
    post:
      description: "Adds or updates tokens to receive push notifications"
      parameters:
      - name: "pushApplicationName"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/push/{pushApplicationName}/removeInstallation:
    post:
      description: "Deactivates tokens to receive push notifications"
      parameters:
      - name: "pushApplicationName"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
