---
openapi: "3.0.1"
info:
  title: "CMDB Meta API"
  description: "Allows you to read metadata information for any CMDB class"
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/cmdb/meta/{className}:
    get:
      description: "Query metadata for a CMDB class"
      parameters:
      - name: "className"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
