---
openapi: "3.0.1"
info:
  title: "GraphQL API"
  description: "Allows you to execute GraphQL requests"
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/graphql:
    get:
      description: "Submit a GraphQL query"
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
    post:
      description: "Submit a GraphQL query"
      parameters: []
      requestBody:
        content:
          application/json: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            multipart/mixed: {}
