---
openapi: "3.0.1"
info:
  title: "passwordexclusionlist"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/passwordexclusionlist/progress_worker_state/{workerId}:
    post:
      description: ""
      parameters:
      - name: "workerId"
        in: "path"
        required: true
        schema: {}
      - name: "workerId"
        in: "query"
        description: "A progress worker ID that can be used to check the progress\
          \ state"
        required: false
        schema: {}
        example: "system id"
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/passwordexclusionlist/reinstall:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/passwordexclusionlist/set_group/{group_id}:
    post:
      description: ""
      parameters:
      - name: "group_id"
        in: "path"
        required: true
        schema: {}
      - name: "group_id"
        in: "query"
        description: "ID for an exclusion list group to act on"
        required: false
        schema: {}
        example: "3"
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/passwordexclusionlist/uninstall:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
