---
openapi: "3.0.1"
info:
  title: "Schedule Page API"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/schedule_page/event/{schedule_page_sys_id}:
    get:
      description: ""
      parameters:
      - name: "schedule_page_sys_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
    put:
      description: ""
      parameters:
      - name: "schedule_page_sys_id"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/schedule_page/info/{info_type}/{schedule_page_sys_id}:
    get:
      description: ""
      parameters:
      - name: "info_type"
        in: "path"
        required: true
        schema: {}
      - name: "schedule_page_sys_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
    put:
      description: ""
      parameters:
      - name: "info_type"
        in: "path"
        required: true
        schema: {}
      - name: "schedule_page_sys_id"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/schedule_page/{schedule_page_sys_id}:
    get:
      description: ""
      parameters:
      - name: "schedule_page_sys_id"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
