---
openapi: "3.0.1"
info:
  title: "Guided Setup API (Internal API)"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/guided_setup/change/log/update:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
  /api/now/guided_setup/content/children/{contentTable}/{parentId}:
    get:
      description: ""
      parameters:
      - name: "contentTable"
        in: "path"
        required: true
        schema: {}
      - name: "parentId"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
  /api/now/guided_setup/content/{contentId}:
    get:
      description: ""
      parameters:
      - name: "contentId"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
  /api/now/guided_setup/content/{contentId}/root:
    get:
      description: ""
      parameters:
      - name: "contentId"
        in: "path"
        required: true
        schema: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
  /api/now/guided_setup/embedded_help/actions/{content}/{action}:
    post:
      description: ""
      parameters:
      - name: "content"
        in: "path"
        required: true
        schema: {}
      - name: "action"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
  /api/now/guided_setup/nav/{action}:
    put:
      description: ""
      parameters:
      - name: "action"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
  /api/now/guided_setup/task/update:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
