---
openapi: "3.0.1"
info:
  title: "CMDB Workspace API (scoped)"
  description: "An API for the CMDB Workspace scoped app intended for all endpoints."
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/sn_cmdb_ws/cmdb_workspace_api_scoped/attestation/action:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/sn_cmdb_ws/cmdb_workspace_api_scoped/certification/action:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/sn_cmdb_ws/cmdb_workspace_api_scoped/imp_action_card:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/sn_cmdb_ws/cmdb_workspace_api_scoped/imp_action_config:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/sn_cmdb_ws/cmdb_workspace_api_scoped/lifecycle_task/action:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/sn_cmdb_ws/cmdb_workspace_api_scoped/nlq/process:
    post:
      description: ""
      parameters:
      - name: "origin"
        in: "query"
        description: "NLQ origin code"
        required: false
        schema: {}
        example: ""
      - name: "user_question"
        in: "query"
        description: "User question utterance"
        required: false
        schema: {}
        example: ""
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/sn_cmdb_ws/cmdb_workspace_api_scoped/nlq/suggest:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/sn_cmdb_ws/cmdb_workspace_api_scoped/nlq/validate:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/sn_cmdb_ws/cmdb_workspace_api_scoped/nlq_query_log:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/sn_cmdb_ws/cmdb_workspace_api_scoped/policy_aggregate_count:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/sn_cmdb_ws/cmdb_workspace_api_scoped/recommendation_card:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/sn_cmdb_ws/cmdb_workspace_api_scoped/recommendation_configs:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/sn_cmdb_ws/cmdb_workspace_api_scoped/sample_search:
    get:
      description: "Gets the list of NLQ sample searches and their associated table\
        \ and labels"
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/sn_cmdb_ws/cmdb_workspace_api_scoped/smartdetection/action:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
