---
openapi: "3.0.1"
info:
  title: "Table Builder Flows integration"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/sn_table_builder/flows/list:
    get:
      description: "Get list of flow."
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
